import { IProject } from './interfaces';

export const metadata = {
  url: 'https://znidar.dev',
  siteName: 'Miha Žnidar',
  locale: 'en_US',
  title: 'Miha Žnidar - Full-Stack Web Developer',
  description:
    'Miha Žnidar is a full-stack web developer from Slovenia. Portfolio of web apps, blockchain projects, and client work. Open to new projects.',
  image: '/assets/metadata.png',
  googleSiteVerification: '6QgNpyUunNctzrJ9dlKxlVbAT9DuOURhu28mlek6JQQ',
  keywords: [
    'Miha Žnidar',
    'full-stack developer',
    'web developer Slovenia',
    'React developer',
    'Next.js developer',
    'TypeScript',
    'portfolio',
    'freelance web developer',
  ],
  knowsAbout: [
    'Web Development',
    'React',
    'Next.js',
    'TypeScript',
    'Node.js',
    'Blockchain',
    'AR/VR',
  ],
  author: {
    name: 'Miha Žnidar',
    email: 'miha.znidar7@gmail.com',
    jobTitle: 'Full-Stack Web Developer',
    country: 'Slovenia',
  },
  social: {
    linkedin: 'https://www.linkedin.com/in/miha-%C5%BEnidar',
    github: 'https://github.com/mayki0909',
  },
}

export const projects: IProject[] = [
  {
    id: 93,
    name: 'Krgofix',
    slug: 'krgofix',
    shortDescription: 'E-mobility webshop and admin platform',
    description: 'Customer-facing Slovenian webshop for electric scooters, e-bikes, refurbished vehicles, and spare parts — with rentals, service booking, vehicle buyback, branch locations, and online payments. Includes a secure admin dashboard for day-to-day operations.',
    aboutProject: 'Built as two Next.js applications that share a Supabase database and common UI components: a public storefront (https://www.krgofix.si/) and an internal admin app. The storefront covers product catalog, checkout, equipment rentals, service and buyback requests, and store locations in Kranj and Jesenice. The admin dashboard supports managers, workers, and partners with webshop operations, service and KranFix jobs, buybacks, rentals, business settings, monthly analytics, and partner payouts.',
    url: 'https://www.krgofix.si/',
    createdAt: new Date(2026, 6, 1).toDateString(),
    image: 'krgofix.webp',
    creativeImage: '',
    roles: ['Frontend', 'Backend'],
    technologies: ['Next.js', 'React', 'TypeScript', 'Supabase', 'Git'],
  },
  {
    id: 94,
    name: 'TK Triglav Kranj',
    slug: 'tk-triglav',
    shortDescription: 'Tennis club website',
    description: 'Modern website for Teniški klub Triglav Kranj — tennis school, competitive and recreational tennis, court reservations (outdoor clay and indoor hard courts), news, pricing, and club info.',
    aboutProject: 'Built with Next.js and deployed on Vercel (https://www.tktriglav.si/). The site covers club activities (teniška šola, tekmovalni and rekreativni tenis), online court reservations for summer and indoor seasons, news, pricing, membership documents, and contact — with a responsive design for desktop and mobile.',
    url: 'https://www.tktriglav.si/',
    createdAt: new Date(2026, 4, 1).toDateString(),
    image: 'tktriglav.webp',
    creativeImage: '',
    roles: ['Frontend', 'Backend'],
    technologies: ['Next.js', 'React', 'TypeScript', 'Vercel', 'Git'],
  },
  {
    id: 95,
    name: 'Savne Dolium',
    slug: 'savne-dolium',
    shortDescription: 'Outdoor saunas and wooden tubs webshop',
    description: 'Slovenian e-commerce site for outdoor Finnish saunas, wooden and hot tubs, garden buildings, stoves, and accessories — with product catalog, sale section, mobile sauna rental, custom sauna inquiries, and contact.',
    aboutProject: 'Customer-facing Next.js webshop for Savne Dolium (https://savne-dolium.si/). Visitors can browse saunas (barrel, square, luxury, indoor, IR), tubs (wooden, massage, ice), garden furniture and glamping cabins, heaters, and add-ons; shop online, explore clearance deals, request mobile sauna rental for events, and get info on delivery, custom builds, and foundation setup. Built with Next.js and React.',
    url: 'https://savne-dolium.si/',
    createdAt: new Date(2025, 3, 1).toDateString(),
    image: 'savne-dolium.webp',
    creativeImage: '',
    roles: ['Frontend', 'Backend'],
    technologies: ['Next.js', 'React', 'TypeScript', 'Git'],
  },
  {
    id: 96,
    name: 'Clout.art',
    slug: 'clout.art',
    shortDescription: 'NFT Minting Platform',
    description: 'Web application for minting NFTs from Instagram posts and files. Helping independet small creators to learn and create their first NFTs.',
    aboutProject: 'Web application is written in Next.js and using NodeJs and MongoDb as backend. In application is integrated smart contract for Hedera Hashgraph network (first was implemented Matic, but we changed to Hedera). I have been working on this project from the start when we were building MVP app. After getting investment we started building bigger platform for helping indepedent creators. I have been working on all parts of application (frontend, backend, devOps, integrating smart contract ...)',
    url: 'http://www.clout.art',
    createdAt: new Date(2022,12,1).toDateString(),
    image: 'cloutart.jpg',
    creativeImage: '',
    roles: ['Frontend', 'Backend'],
    technologies: ['Solidity', 'React', 'Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Git'],
  },
  {
    id: 97,
    name: 'Plankebordene',
    slug: 'plankebordene',
    shortDescription: 'Web application for ordering custom made wooden tables.',
    description: 'Configurator and online shop. Its special feature is a configurator that guides you through the creation and ordering of a custom table in less than 5 minutes.',
    aboutProject: 'The web application is written in React.js, optimised for computer and mobile screens. I worked on the project as project manager and front-end developer and was involved in the whole development process. I started with requirements analysis and document preparation. With the successful completion of the project, I proved to myself that I have learned a lot in 3 years of programming. I also gained many other skills from the IT world (communicating with clients, preparing documentation, managing and coordinating a small team).',
    url: 'https://plankebordene.starc.media',
    createdAt: new Date(2022,5,1).toDateString(),
    image: 'plankebordene.webp',
    creativeImage: '',
    roles: ['Product owner', 'Team lead', 'Frontend'],
    technologies: ['React', 'TypeScript', 'NodeJs' ,'MongoDb', 'Docker', 'Git', 'Figma']
  },
  {
    id: 98,
    name: 'AXM Electric',
    slug: 'axm',
    shortDescription: 'Static website focused on SEO',
    description: 'Website created for same customer as QLR focused on SEO optimization.',
    aboutProject: 'It is static website focused on SEO and presentation of 4 electric motors. The website was crafted with precision, using HTML5, CSS3, JavaScript and Bootstrap to provide a visually striking, user-friendly and resposive design.',
    url: 'https://mayki0909.github.io/AXM/',
    createdAt: new Date(2021,11,17).toDateString(),
    image: 'axm_electric.webp',
    creativeImage: 'projectCreative.png',
    roles: ['Frontend'],
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'Bootstrap', 'SEO']
  },
  // {
  //   id: 99,
  //   name: 'QLR',
  //   slug: 'qlr',
  //   shortDescription: 'Static website',
  //   description: 'Website created based on customers wishes.',
  //   aboutProject: 'Primary goals of website were to present an electric motocycle, create brand awareness and raise funds for the production of the motocycle. Website was created by using HTML5, CSS3, Javascript and Bootstrap to provide resposive design.',
  //   url: 'https://mayki0909.github.io/QLR/',
  //   createdAt: new Date(2019,12,15).toDateString(),
  //   image: 'qlr.webp',
  //   creativeImage: '',
  //   roles: ['Frontend'],
  //   technologies: ['HTML5', 'CSS3', 'JavaScript', 'Bootstrap']
  // },
  // {
  //   id: 102,
  //   name: 'Endless Runner',
  //   slug: 'endless-runner',
  //   shortDescription: 'Mobile game for android',
  //   description: "For graduation project in high school I created android mobile game  using Unity Game Engine using C# programming language.",
  //   aboutProject: "It is endless runner type of game. Where the player controls the characters's jumping by clicking on the screen, and holding the press longer lead to a higher jump. The objective of the game is to collect coins while avoiding obstacles. As the game progresses, the platforms move faster, increasing the difficulty level and challenging the player.",
  //   url: 'https://github.com/mayki0909/Endless-Runner',
  //   createdAt: new Date(2019,4,10,).toDateString(),
  //   image: 'endless_runner.webp',
  //   creativeImage: '',
  //   roles: ['Full-stack'],
  //   technologies: ['C#', 'Unity', 'Andorid']
  // }
]